import "../styles/globals.css";
import Script from "next/script";
import { Provider } from "react-redux";
import store from "../Redux/store";
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Library Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
    </>
  );
}
