import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const dummy_Data=[
    {id:1,name:"next",author:"ekta",total:12},{id:2,name:"react",author:"kushagra",total:14},{id:3,name:"Js",author:"sundar",total:22}
]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
   <h1>
    Welcome to library management
   </h1>
  <Link href="/adminPage"> <h2>Enter as admin</h2></Link>
   <Link href="/member-login"><h1>Enter as student</h1></Link>
      </main>
    </>
  )
}
